In [1]:
import matplotlib.pylab as pl
import numpy as np
import xgboost
from sklearn.model_selection import train_test_split

import shap

/home/rizkiduwinanto/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
X, y = shap.datasets.nhanesi()

In [3]:
X

sex_isFemale  age  physical_activity  serum_albumin  \
20751         False   51                  3            NaN   
20753         False   41                  2            NaN   
20754          True   31                  2            NaN   
20755         False   48                  2            NaN   
20756          True   29                  3            NaN   
...             ...  ...                ...            ...   
25043          True   63                  2            NaN   
25046          True   56                  2            NaN   
25049          True   47                  2            NaN   
25057          True   61                  8            NaN   
25061         False   29                  3            NaN   

       alkaline_phosphatase  alkaline_phosphatase_isUnacceptable  \
20751                  85.0                                False   
20753                  68.0                                False   
20754                  61.0                                False   
20755                  58.0                                False   
20756                  37.0                                False   
...                     ...                                  ...   
25043                  86.0                                False   
25046                  65.0                                False   
25049                  46.0                                False   
25057                  75.0                                False   
25061                  84.0                                False   

       alkaline_phosphatase_isTestnotdone  SGOT  SGOT_isUnacceptable  \
20751                               False   NaN                 True   
20753                               False  2.27                False   
20754                               False  1.86                False   
20755                               False   NaN                 True   
20756                               False  1.69                False   
...                                   ...   ...                  ...   
25043                               False  2.24                False   
25046                               False  2.31                False   
25049                               False  1.93                False   
25057                               False  2.29                False   
25061                               False  3.02                False   

       SGOT_isTestnotdone  ...  urine_hematest_isLarge  \
20751               False  ...                   False   
20753               False  ...                   False   
20754               False  ...                   False   
20755               False  ...                   False   
20756               False  ...                   False   
...                   ...  ...                     ...   
25043               False  ...                   False   
25046               False  ...                   False   
25049               False  ...                   False   
25057               False  ...                   False   
25061               False  ...                   False   

       urine_hematest_isBlankbutapplicable  sedimentation_rate  \
20751                                False                 NaN   
20753                                False                 NaN   
20754                                False                 NaN   
20755                                False                 NaN   
20756                                False                 NaN   
...                                    ...                 ...   
25043                                False                 NaN   
25046                                False                 NaN   
25049                                False                 NaN   
25057                                False                 NaN   
25061                                False                 NaN   

       sedimentation_rate_isBlankbutapplicable  uric_acid  \
20751                        

In [4]:
y

array([-16.91666667, -17.16666667, -17.66666667, ..., -17.08333333,
       -17.08333333, -17.08333333])

In [5]:
X_display, y_display = shap.datasets.nhanesi(display=True)


In [6]:
X_display

sex_isFemale  age  physical_activity  serum_albumin  \
20751         False   51                  3            NaN   
20753         False   41                  2            NaN   
20754          True   31                  2            NaN   
20755         False   48                  2            NaN   
20756          True   29                  3            NaN   
...             ...  ...                ...            ...   
25043          True   63                  2            NaN   
25046          True   56                  2            NaN   
25049          True   47                  2            NaN   
25057          True   61                  8            NaN   
25061         False   29                  3            NaN   

       alkaline_phosphatase  alkaline_phosphatase_isUnacceptable  \
20751                  85.0                                False   
20753                  68.0                                False   
20754                  61.0                                False   
20755                  58.0                                False   
20756                  37.0                                False   
...                     ...                                  ...   
25043                  86.0                                False   
25046                  65.0                                False   
25049                  46.0                                False   
25057                  75.0                                False   
25061                  84.0                                False   

       alkaline_phosphatase_isTestnotdone  SGOT  SGOT_isUnacceptable  \
20751                               False   NaN                 True   
20753                               False  2.27                False   
20754                               False  1.86                False   
20755                               False   NaN                 True   
20756                               False  1.69                False   
...                                   ...   ...                  ...   
25043                               False  2.24                False   
25046                               False  2.31                False   
25049                               False  1.93                False   
25057                               False  2.29                False   
25061                               False  3.02                False   

       SGOT_isTestnotdone  ...  urine_hematest_isLarge  \
20751               False  ...                   False   
20753               False  ...                   False   
20754               False  ...                   False   
20755               False  ...                   False   
20756               False  ...                   False   
...                   ...  ...                     ...   
25043               False  ...                   False   
25046               False  ...                   False   
25049               False  ...                   False   
25057               False  ...                   False   
25061               False  ...                   False   

       urine_hematest_isBlankbutapplicable  sedimentation_rate  \
20751                                False                 NaN   
20753                                False                 NaN   
20754                                False                 NaN   
20755                                False                 NaN   
20756                                False                 NaN   
...                                    ...                 ...   
25043                                False                 NaN   
25046                                False                 NaN   
25049                                False                 NaN   
25057                                False                 NaN   
25061                                False                 NaN   

       sedimentation_rate_isBlankbutapplicable  uric_acid  \
20751                        

In [7]:
y_display

array([-16.91666667, -17.16666667, -17.66666667, ..., -17.08333333,
       -17.08333333, -17.08333333])

In [9]:
X_display.fillna(X_display.median())

sex_isFemale  age  physical_activity  serum_albumin  \
20751         False   51                  3            4.4   
20753         False   41                  2            4.4   
20754          True   31                  2            4.4   
20755         False   48                  2            4.4   
20756          True   29                  3            4.4   
...             ...  ...                ...            ...   
25043          True   63                  2            4.4   
25046          True   56                  2            4.4   
25049          True   47                  2            4.4   
25057          True   61                  8            4.4   
25061         False   29                  3            4.4   

       alkaline_phosphatase  alkaline_phosphatase_isUnacceptable  \
20751                  85.0                                False   
20753                  68.0                                False   
20754                  61.0                                False   
20755                  58.0                                False   
20756                  37.0                                False   
...                     ...                                  ...   
25043                  86.0                                False   
25046                  65.0                                False   
25049                  46.0                                False   
25057                  75.0                                False   
25061                  84.0                                False   

       alkaline_phosphatase_isTestnotdone  SGOT  SGOT_isUnacceptable  \
20751                               False  2.20                 True   
20753                               False  2.27                False   
20754                               False  1.86                False   
20755                               False  2.20                 True   
20756                               False  1.69                False   
...                                   ...   ...                  ...   
25043                               False  2.24                False   
25046                               False  2.31                False   
25049                               False  1.93                False   
25057                               False  2.29                False   
25061                               False  3.02                False   

       SGOT_isTestnotdone  ...  urine_hematest_isLarge  \
20751               False  ...                   False   
20753               False  ...                   False   
20754               False  ...                   False   
20755               False  ...                   False   
20756               False  ...                   False   
...                   ...  ...                     ...   
25043               False  ...                   False   
25046               False  ...                   False   
25049               False  ...                   False   
25057               False  ...                   False   
25061               False  ...                   False   

       urine_hematest_isBlankbutapplicable  sedimentation_rate  \
20751                                False                14.0   
20753                                False                14.0   
20754                                False                14.0   
20755                                False                14.0   
20756                                False                14.0   
...                                    ...                 ...   
25043                                False                14.0   
25046                                False                14.0   
25049                                False                14.0   
25057                                False                14.0   
25061                                False                14.0   

       sedimentation_rate_isBlankbutapplicable  uric_acid  \
20751                        

In [11]:
from dataset import NHANESDataset

dataset = NHANESDataset()
data = dataset.get_data()

/mnt/c/Users/rizki/Master Files/ThesisUMCG/Survival-Tree-Analysis/src/dataset.py:210: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.data.replace({False: 0, True: 1}, inplace=True)


In [12]:
data

array([[  0.        ,  51.        ,   3.        , ..., 110.        ,
         40.        ,  25.40680287],
       [  0.        ,  41.        ,   2.        , ..., 136.        ,
         54.        ,  24.58833109],
       [  1.        ,  31.        ,   2.        , ..., 110.        ,
         24.        ,  23.75650236],
       ...,
       [  1.        ,  47.        ,   2.        , ..., 108.        ,
         28.        ,  17.9151988 ],
       [  1.        ,  61.        ,   8.        , ..., 180.        ,
         68.        ,  27.33162171],
       [  0.        ,  29.        ,   3.        , ..., 152.        ,
         60.        ,  33.16143518]])